### ISSUE TITLE
Excessive memory consumption?

### ISSUE THREAD

**Issue by looztra** [salesforce/sloop#112]
We are currently experimenting to use sloop.

We find it very useful but we found out that it was very greedy regarding memory.
After less than a full day, it is currently using 5Gb of memory :(

Is it the normal behaviour?

The last 3 hours
![sloop-last-3hours-2020 04 08-16_19_41](https://user-images.githubusercontent.com/246526/78795173-fa61a980-79b4-11ea-92a8-877ffb31e475.png)

The last 24 hours
![sloop-last-24hours-2020 04 08-16_20_06](https://user-images.githubusercontent.com/246526/78795230-0ea5a680-79b5-11ea-8fa8-bf9f5b3aad6a.png)

Here is our current configuration (no memory limits on purpose to see what's needed without being OOM killed)

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sloop
  labels:
    app.kubernetes.io/name: sloop
spec:
  serviceName: sloop
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sloop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sloop
    spec:
      containers:
        - args:
            - --config=/sloop-config/sloop.json
          command:
            - /sloop
          image: FIXME/sloop
          name: sloop
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits: {}
            requests:
              memory: 1.5Gi
              cpu: 50m
          volumeMounts:
            - mountPath: /data
              name: sloop-data
            - mountPath: /sloop-config
              name: sloop-config
            - mountPath: /tmp
              name: sloop-tmp
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 1000
            readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
      volumes:
        - name: sloop-config
          configMap:
            name: sloop-config
        - name: sloop-tmp
          emptyDir:
            sizeLimit: 100Mi
      serviceAccountName: sloop
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: sloop-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```
