### ISSUE TITLE
Value log truncate required to run DB.

### ISSUE THREAD

**Issue by alexppg** [salesforce/sloop#178]
Hi
I'm using sloop in k8s and after some days running without problem, the pod enters in a CrashLoopBackOff state and doesn't change. 

My helm configuration is:

```yaml
---
serviceAccountName: sloop
name: sloop
replicas: 1
persistentVolume:
  size: 10Gi
  dataAccessMode: ReadWriteOnce
  sizeLimit: 12Gi
  storageClass: openebs-jiva
ingress:
  enabled: true
  host: sloop.example.com
  annotations:
    kubernetes.io/ingress.class: ingress-admin
resources:
  limits:
    cpu: 200m
    memory: 10240Mi
  requests:
    cpu: 100m
    memory: 500Mi
clusterRole:
  apiGroups:
    - alertmanagers.monitoring.coreos.com
    - bgpconfigurations.crd.projectcalico.org
    - bgppeers.crd.projectcalico.org
    - blockaffinities.crd.projectcalico.org
    - blockdeviceclaims.openebs.io

# The badger configuration is from: https://github.com/salesforce/sloop#memory-consumption
config: |-
  {
    "badgerUseLSMOnlyOptions": false,
    "badgerKeepL0InMemory": false,
    "badgerSyncWrites": false,
    "badgerVLogFileIOMapping": true,
    "badgerMaxTableSize": 524288,
    "badgerNumOfCompactors": 1,
    "badgerNumLevelZeroTables": 1,
    "badgerNumLevelZeroTablesStall": 2,
    "badgerVLogTruncate": true,
    "displayContext": "cluster",
    "defaultNamespace": "default",
    "defaultKind": "Pod",
    "defaultLookback": "1h",
    "leftBarLinks": [
    ],
    "resourceLinks": [
    ]
  }
```

I've used the configuration mentioned [here](https://github.com/salesforce/sloop#memory-consumption) (which BTW I believe is not correct, since the json doesn't read the value **badger-max-table-size** but **badgerMaxTableSize**, as far as I've read [here](https://github.com/salesforce/sloop/blob/63b3d51552e9e2dd7a0adccab57e0bdd8a32ee4e/pkg/sloop/server/internal/config/config.go#L61).

Anywhere in the project it's mentioned the necessity of truncating the log, but I've use it anyways and the results is always the same. 

The disk has unused space.

Any hint?
